site_name: Crystal
site_url: https://oprypin.github.io/crystal-book
repo_url: https://github.com/oprypin/crystal-book
edit_uri: tree/mkdocstrings/docs/
use_directory_urls: false

theme:
  name: material
  palette:
    primary: black
    accent: blue
  icon:
    repo: fontawesome/brands/github
  favicon: https://crystal-lang.org/favicon.ico
  logo: assets/crystal-circ.svg
  features:
    - navigation.tabs

extra_css:
  - assets/vendor/codemirror/codemirror.min.css
  - assets/style.css
  - assets/vendor/carcin-play/carcin-play.css
  - assets/vendor/carcin-play/codemirror-theme.css

extra_css:
  - css/mkdocstrings.css

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - mkdocstrings:
      default_handler: crystal
      watch: [src]
      handlers:
        crystal:
          crystal_docs_flags:
            - --project-name=Crystal
            - crystal/src/docs_main.cr
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - redirects:
      redirect_maps:
        introduction.md: README.md
        syntax_and_semantics/literals.md: syntax_and_semantics/literals/README.md
        syntax_and_semantics/macros.md: syntax_and_semantics/macros/README.md
        syntax_and_semantics/annotations.md: syntax_and_semantics/annotations/README.md
        guides/continuous_integration.md: guides/ci/README.md
        conventions/documenting_code.md: syntax_and_semantics/documenting_code.md
        docs/overview/README.md: syntax_and_semantics/README.md

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - deduplicate-toc
  - toc:
      permalink: true
  - pymdownx.snippets

google_analytics:
  - UA-42353458-1
  - auto

extra_javascript:
  - assets/vendor/codemirror/codemirror.min.js
  - assets/vendor/codemirror/mode/crystal/crystal.min.js
  - assets/vendor/carcin-play/carcin.js
  - assets/vendor/carcin-play/carcin-play.js
  - assets/vendor/ansi_up/ansi_up.min.js
  - assets/crystal-play.js
