name: Deploy book
on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * 1'  # Every Monday 6 AM UTC
jobs:
  build:
    name: Deploy book
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('requirements.txt') }}
          restore-keys: pip-
      - name: Install dependencies
        run: pip install --no-deps -r requirements.txt
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
      - name: Download Crystal source
        uses: actions/checkout@v2
        with:
          repository: crystal-lang/crystal
          path: crystal
      - name: Build site
        run: PATH="$(pwd)/crystal/bin:$PATH" mkdocs build
      - name: Disallow unchecked intra-site links
        run: make check_internal_links
      - name: Deploy to gh-pages
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref == 'refs/heads/mkdocstrings'
        uses: oprypin/push-to-gh-pages@v3
        with:
          publish_dir: site
          commit_message: 'Generate docs: '
